namespace DM_OHD.FRM
{
    partial class FRM_PRODUCTION_PLAN
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabFY;
        private System.Windows.Forms.TabPage tabRatio;
        private System.Windows.Forms.TabPage tabOutput;
        private System.Windows.Forms.TabPage tabMaster;
        private DevExpress.XtraGrid.GridControl gridFY;
        private DevExpress.XtraGrid.Views.Grid.GridView viewFY;
        private DevExpress.XtraGrid.Columns.GridColumn colSelectFY;
        private DevExpress.XtraGrid.GridControl gridRatio;
        private DevExpress.XtraGrid.Views.Grid.GridView viewRatio;
        private DevExpress.XtraGrid.Columns.GridColumn colSelectRatio;
        private DevExpress.XtraGrid.GridControl gridOutput;
        private DevExpress.XtraGrid.Views.Grid.GridView viewOutput;
        private DevExpress.XtraGrid.Columns.GridColumn colSelectOutput;
        private DevExpress.XtraGrid.GridControl gridMaster;
        private DevExpress.XtraGrid.Views.Grid.GridView viewMaster;
        private DevExpress.XtraEditors.SimpleButton btnSaveFY;
        private DevExpress.XtraEditors.SimpleButton btnSaveRatio;
        private DevExpress.XtraEditors.SimpleButton btnSaveOutput;
        private DevExpress.XtraEditors.SimpleButton btnSaveMaster;
        private DevExpress.XtraEditors.SimpleButton btnGenerateMaster;
        private DevExpress.XtraEditors.SimpleButton btnExportFY;
        private DevExpress.XtraEditors.SimpleButton btnImportFY;
        private DevExpress.XtraEditors.SimpleButton btnExportRatio;
        private DevExpress.XtraEditors.SimpleButton btnImportRatio;
        private DevExpress.XtraEditors.SimpleButton btnExportOutput;
        private DevExpress.XtraEditors.SimpleButton btnDeleteFY;
        private DevExpress.XtraEditors.SimpleButton btnDeleteRatio;
        private DevExpress.XtraEditors.SimpleButton btnDeleteOutput;
        private DevExpress.XtraEditors.SimpleButton btnImportOutput;
        private DevExpress.XtraEditors.SimpleButton btnExportMaster;
        private DevExpress.XtraEditors.PanelControl panelFilter;
        private DevExpress.XtraEditors.LabelControl lblFrom;
        private DevExpress.XtraEditors.LabelControl lblTo;
        private DevExpress.XtraEditors.DateEdit deFrom;
        private DevExpress.XtraEditors.DateEdit deTo;
        private DevExpress.XtraEditors.SimpleButton btnApplyFilter;
        private DevExpress.XtraEditors.SimpleButton btnTemplateFY;
        private DevExpress.XtraEditors.SimpleButton btnTemplateRatio;
        private DevExpress.XtraEditors.SimpleButton btnTemplateOutput;
        private DevExpress.XtraEditors.SimpleButton btnTemplateMaster;
        private System.Windows.Forms.FlowLayoutPanel panelFYActions;
        private System.Windows.Forms.FlowLayoutPanel panelRatioActions;
        private System.Windows.Forms.FlowLayoutPanel panelOutputActions;
        private System.Windows.Forms.FlowLayoutPanel panelMasterActions;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabFY = new System.Windows.Forms.TabPage();
            this.tabRatio = new System.Windows.Forms.TabPage();
            this.tabOutput = new System.Windows.Forms.TabPage();
            this.tabMaster = new System.Windows.Forms.TabPage();
            this.gridFY = new DevExpress.XtraGrid.GridControl();
            this.viewFY = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colSelectFY = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridRatio = new DevExpress.XtraGrid.GridControl();
            this.viewRatio = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colSelectRatio = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridOutput = new DevExpress.XtraGrid.GridControl();
            this.viewOutput = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.colSelectOutput = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridMaster = new DevExpress.XtraGrid.GridControl();
            this.viewMaster = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.btnSaveFY = new DevExpress.XtraEditors.SimpleButton();
            this.btnSaveRatio = new DevExpress.XtraEditors.SimpleButton();
            this.btnSaveOutput = new DevExpress.XtraEditors.SimpleButton();
            this.btnSaveMaster = new DevExpress.XtraEditors.SimpleButton();
            this.btnGenerateMaster = new DevExpress.XtraEditors.SimpleButton();
            this.btnExportFY = new DevExpress.XtraEditors.SimpleButton();
            this.btnImportFY = new DevExpress.XtraEditors.SimpleButton();
            this.btnExportRatio = new DevExpress.XtraEditors.SimpleButton();
            this.btnImportRatio = new DevExpress.XtraEditors.SimpleButton();
            this.btnExportOutput = new DevExpress.XtraEditors.SimpleButton();
            this.btnDeleteFY = new DevExpress.XtraEditors.SimpleButton();
            this.btnDeleteRatio = new DevExpress.XtraEditors.SimpleButton();
            this.btnDeleteOutput = new DevExpress.XtraEditors.SimpleButton();
            this.btnImportOutput = new DevExpress.XtraEditors.SimpleButton();
            this.btnExportMaster = new DevExpress.XtraEditors.SimpleButton();
            this.panelFilter = new DevExpress.XtraEditors.PanelControl();
            this.lblFrom = new DevExpress.XtraEditors.LabelControl();
            this.lblTo = new DevExpress.XtraEditors.LabelControl();
            this.deFrom = new DevExpress.XtraEditors.DateEdit();
            this.deTo = new DevExpress.XtraEditors.DateEdit();
            this.btnApplyFilter = new DevExpress.XtraEditors.SimpleButton();
            this.btnTemplateFY = new DevExpress.XtraEditors.SimpleButton();
            this.btnTemplateRatio = new DevExpress.XtraEditors.SimpleButton();
            this.btnTemplateOutput = new DevExpress.XtraEditors.SimpleButton();
            this.btnTemplateMaster = new DevExpress.XtraEditors.SimpleButton();
            this.panelFYActions = new System.Windows.Forms.FlowLayoutPanel();
            this.panelRatioActions = new System.Windows.Forms.FlowLayoutPanel();
            this.panelOutputActions = new System.Windows.Forms.FlowLayoutPanel();
            this.panelMasterActions = new System.Windows.Forms.FlowLayoutPanel();
            this.tabControl1.SuspendLayout();
            this.tabFY.SuspendLayout();
            this.tabRatio.SuspendLayout();
            this.tabOutput.SuspendLayout();
            this.tabMaster.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridFY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewFY)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridRatio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewRatio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridOutput)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewOutput)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewMaster)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.panelFilter)).BeginInit();
            this.panelFilter.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deFrom.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.deFrom.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.deTo.Properties.CalendarTimeProperties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.deTo.Properties)).BeginInit();
            this.SuspendLayout();
            // tabControl
            this.tabControl1.Controls.Add(this.tabFY);
            this.tabControl1.Controls.Add(this.tabRatio);
            this.tabControl1.Controls.Add(this.tabOutput);
            this.tabControl1.Controls.Add(this.tabMaster);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 42);
            this.tabControl1.Size = new System.Drawing.Size(1280, 678);

            // tab FY
            this.tabFY.Controls.Add(this.gridFY);
            this.tabFY.Controls.Add(this.panelFYActions);
            this.tabFY.Text = "Bảng 2 - Kế hoạch FY";
            this.tabFY.UseVisualStyleBackColor = true;
            this.gridFY.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridFY.MainView = this.viewFY;
            this.gridFY.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { this.viewFY });
            this.viewFY.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { this.colSelectFY });
            this.colSelectFY.Caption = "Chọn";
            this.colSelectFY.FieldName = "ROW_SELECTED";
            this.colSelectFY.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.colSelectFY.Visible = true;
            this.colSelectFY.VisibleIndex = 0;
            this.colSelectFY.Width = 52;
            this.panelFYActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelFYActions.Height = 38;
            this.panelFYActions.Padding = new System.Windows.Forms.Padding(6, 6, 6, 4);
            this.panelFYActions.Controls.Add(this.btnSaveFY);
            this.panelFYActions.Controls.Add(this.btnDeleteFY);
            this.panelFYActions.Controls.Add(this.btnTemplateFY);
            this.panelFYActions.Controls.Add(this.btnImportFY);
            this.panelFYActions.Controls.Add(this.btnExportFY);
            this.btnSaveFY.Size = new System.Drawing.Size(170, 26);
            this.btnSaveFY.Text = "Lưu bảng kế hoạch FY";
            this.btnDeleteFY.Size = new System.Drawing.Size(110, 26);
            this.btnDeleteFY.Text = "Xóa dòng chọn";
            this.btnImportFY.Size = new System.Drawing.Size(110, 26);
            this.btnImportFY.Text = "Import Excel";
            this.btnExportFY.Size = new System.Drawing.Size(90, 26);
            this.btnExportFY.Text = "Export";
            this.btnTemplateFY.Size = new System.Drawing.Size(120, 26);
            this.btnTemplateFY.Text = "Lưu form import";

            // tab Ratio
            this.tabRatio.Controls.Add(this.gridRatio);
            this.tabRatio.Controls.Add(this.panelRatioActions);
            this.tabRatio.Text = "Bảng 3 - Tỉ lệ chạy máy";
            this.tabRatio.UseVisualStyleBackColor = true;
            this.gridRatio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridRatio.MainView = this.viewRatio;
            this.gridRatio.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { this.viewRatio });
            this.viewRatio.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { this.colSelectRatio });
            this.colSelectRatio.Caption = "Chọn";
            this.colSelectRatio.FieldName = "ROW_SELECTED";
            this.colSelectRatio.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.colSelectRatio.Visible = true;
            this.colSelectRatio.VisibleIndex = 0;
            this.colSelectRatio.Width = 52;
            this.panelRatioActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelRatioActions.Height = 38;
            this.panelRatioActions.Padding = new System.Windows.Forms.Padding(6, 6, 6, 4);
            this.panelRatioActions.Controls.Add(this.btnSaveRatio);
            this.panelRatioActions.Controls.Add(this.btnDeleteRatio);
            this.panelRatioActions.Controls.Add(this.btnTemplateRatio);
            this.panelRatioActions.Controls.Add(this.btnImportRatio);
            this.panelRatioActions.Controls.Add(this.btnExportRatio);
            this.btnSaveRatio.Size = new System.Drawing.Size(170, 26);
            this.btnSaveRatio.Text = "Lưu bảng tỉ lệ chạy máy";
            this.btnDeleteRatio.Size = new System.Drawing.Size(110, 26);
            this.btnDeleteRatio.Text = "Xóa dòng chọn";
            this.btnImportRatio.Size = new System.Drawing.Size(110, 26);
            this.btnImportRatio.Text = "Import Excel";
            this.btnExportRatio.Size = new System.Drawing.Size(90, 26);
            this.btnExportRatio.Text = "Export";
            this.btnTemplateRatio.Size = new System.Drawing.Size(120, 26);
            this.btnTemplateRatio.Text = "Lưu form import";

            // tab Output
            this.tabOutput.Controls.Add(this.gridOutput);
            this.tabOutput.Controls.Add(this.panelOutputActions);
            this.tabOutput.Text = "Bảng 4 - Sản lượng khuôn";
            this.tabOutput.UseVisualStyleBackColor = true;
            this.gridOutput.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridOutput.MainView = this.viewOutput;
            this.gridOutput.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { this.viewOutput });
            this.viewOutput.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] { this.colSelectOutput });
            this.colSelectOutput.Caption = "Chọn";
            this.colSelectOutput.FieldName = "ROW_SELECTED";
            this.colSelectOutput.Fixed = DevExpress.XtraGrid.Columns.FixedStyle.Left;
            this.colSelectOutput.Visible = true;
            this.colSelectOutput.VisibleIndex = 0;
            this.colSelectOutput.Width = 52;
            this.panelOutputActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelOutputActions.Height = 38;
            this.panelOutputActions.Padding = new System.Windows.Forms.Padding(6, 6, 6, 4);
            this.panelOutputActions.Controls.Add(this.btnSaveOutput);
            this.panelOutputActions.Controls.Add(this.btnDeleteOutput);
            this.panelOutputActions.Controls.Add(this.btnTemplateOutput);
            this.panelOutputActions.Controls.Add(this.btnImportOutput);
            this.panelOutputActions.Controls.Add(this.btnExportOutput);
            this.btnSaveOutput.Size = new System.Drawing.Size(180, 26);
            this.btnSaveOutput.Text = "Lưu bảng sản lượng khuôn";
            this.btnDeleteOutput.Size = new System.Drawing.Size(110, 26);
            this.btnDeleteOutput.Text = "Xóa dòng chọn";
            this.btnImportOutput.Size = new System.Drawing.Size(110, 26);
            this.btnImportOutput.Text = "Import Excel";
            this.btnExportOutput.Size = new System.Drawing.Size(90, 26);
            this.btnExportOutput.Text = "Export";
            this.btnTemplateOutput.Size = new System.Drawing.Size(120, 26);
            this.btnTemplateOutput.Text = "Lưu form import";

            // tab Master
            this.tabMaster.Controls.Add(this.gridMaster);
            this.tabMaster.Controls.Add(this.panelMasterActions);
            this.tabMaster.Text = "Bảng 1 - Kế hoạch OHD";
            this.tabMaster.UseVisualStyleBackColor = true;
            this.gridMaster.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridMaster.MainView = this.viewMaster;
            this.gridMaster.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { this.viewMaster });
            this.panelMasterActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelMasterActions.Height = 38;
            this.panelMasterActions.Padding = new System.Windows.Forms.Padding(6, 6, 6, 4);
            this.panelMasterActions.Controls.Add(this.btnGenerateMaster);
            this.panelMasterActions.Controls.Add(this.btnSaveMaster);
            this.panelMasterActions.Controls.Add(this.btnTemplateMaster);
            this.panelMasterActions.Controls.Add(this.btnExportMaster);
            this.btnGenerateMaster.Size = new System.Drawing.Size(220, 26);
            this.btnGenerateMaster.Text = "Tạo bảng kế hoạch OHD (master)";
            this.btnSaveMaster.Size = new System.Drawing.Size(120, 26);
            this.btnSaveMaster.Text = "Lưu OHD";
            this.btnExportMaster.Size = new System.Drawing.Size(90, 26);
            this.btnExportMaster.Text = "Export";
            this.btnTemplateMaster.Size = new System.Drawing.Size(120, 26);
            this.btnTemplateMaster.Text = "Lưu form import";

            // panelFilter
            this.panelFilter.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.panelFilter.Controls.Add(this.btnApplyFilter);
            this.panelFilter.Controls.Add(this.deTo);
            this.panelFilter.Controls.Add(this.deFrom);
            this.panelFilter.Controls.Add(this.lblTo);
            this.panelFilter.Controls.Add(this.lblFrom);
            this.panelFilter.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelFilter.Location = new System.Drawing.Point(0, 0);
            this.panelFilter.Name = "panelFilter";
            this.panelFilter.Size = new System.Drawing.Size(1280, 42);
            this.lblFrom.Location = new System.Drawing.Point(10, 13);
            this.lblFrom.Size = new System.Drawing.Size(17, 13);
            this.lblFrom.Text = "Từ";
            this.deFrom.EditValue = null;
            this.deFrom.Location = new System.Drawing.Point(34, 10);
            this.deFrom.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.deFrom.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.deFrom.Size = new System.Drawing.Size(100, 20);
            this.lblTo.Location = new System.Drawing.Point(142, 13);
            this.lblTo.Size = new System.Drawing.Size(21, 13);
            this.lblTo.Text = "Đến";
            this.deTo.EditValue = null;
            this.deTo.Location = new System.Drawing.Point(170, 10);
            this.deTo.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.deTo.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
                new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.deTo.Size = new System.Drawing.Size(100, 20);
            this.btnApplyFilter.Location = new System.Drawing.Point(280, 9);
            this.btnApplyFilter.Size = new System.Drawing.Size(52, 23);
            this.btnApplyFilter.Text = "Lọc";

            // form
            this.ClientSize = new System.Drawing.Size(1280, 720);
            this.Controls.Add(this.tabControl1);
            this.Controls.Add(this.panelFilter);
            this.Text = "Kế hoạch sản xuất";
            this.tabControl1.ResumeLayout(false);
            this.tabFY.ResumeLayout(false);
            this.tabRatio.ResumeLayout(false);
            this.tabOutput.ResumeLayout(false);
            this.tabMaster.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridFY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewFY)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridRatio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewRatio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridOutput)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewOutput)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.viewMaster)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.panelFilter)).EndInit();
            this.panelFilter.ResumeLayout(false);
            this.panelFilter.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.deFrom.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.deFrom.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.deTo.Properties.CalendarTimeProperties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.deTo.Properties)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
