IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_ROLE')
BEGIN
    CREATE TABLE dbo.APP_ROLE (
        ROLE_CODE NVARCHAR(50) NOT NULL PRIMARY KEY,
        ROLE_NAME NVARCHAR(200) NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_USER')
BEGIN
    CREATE TABLE dbo.APP_USER (
        USER_ID NVARCHAR(50) NOT NULL PRIMARY KEY,
        FULL_NAME NVARCHAR(200) NOT NULL,
        PASSWORD_MD5 CHAR(32) NOT NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_APP_USER_ACTIVE DEFAULT(1),
        CREATED_AT DATETIME NOT NULL CONSTRAINT DF_APP_USER_CREATED DEFAULT(GETDATE())
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_USER_ROLE')
BEGIN
    CREATE TABLE dbo.APP_USER_ROLE (
        USER_ID NVARCHAR(50) NOT NULL,
        ROLE_CODE NVARCHAR(50) NOT NULL,
        CONSTRAINT PK_APP_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CODE),
        CONSTRAINT FK_APP_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES dbo.APP_USER(USER_ID),
        CONSTRAINT FK_APP_USER_ROLE_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES dbo.APP_ROLE(ROLE_CODE)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DIE_MST')
BEGIN
    CREATE TABLE dbo.DIE_MST (
        DIE_NO NVARCHAR(50) NOT NULL PRIMARY KEY,
        DIE_NAME NVARCHAR(255) NOT NULL,
        TOTAL_CAVITY INT NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'ADMIN')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ADMIN', N'Quản trị hệ thống');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'ACCOUNT_MGMT')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ACCOUNT_MGMT', N'Quản lý tài khoản');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'DIE_MST_MGMT')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('DIE_MST_MGMT', N'Quản lý Die Master');
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER WHERE USER_ID = 'admin')
BEGIN
    INSERT INTO dbo.APP_USER (USER_ID, FULL_NAME, PASSWORD_MD5, IS_ACTIVE)
    VALUES ('admin', N'System Administrator', '0192023a7bbd73250516f069df18b500', 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'ADMIN')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'ADMIN');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'ACCOUNT_MGMT')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'ACCOUNT_MGMT');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'DIE_MST_MGMT')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'DIE_MST_MGMT');
GO
