IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_ROLE')
BEGIN
    CREATE TABLE dbo.APP_ROLE (
        ROLE_CODE NVARCHAR(50) NOT NULL PRIMARY KEY,
        ROLE_NAME NVARCHAR(200) NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_USER')
BEGIN
    CREATE TABLE dbo.APP_USER (
        USER_ID NVARCHAR(50) NOT NULL PRIMARY KEY,
        FULL_NAME NVARCHAR(200) NOT NULL,
        PASSWORD_MD5 CHAR(32) NOT NULL,
        EMAIL NVARCHAR(255) NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_APP_USER_ACTIVE DEFAULT(1),
        CREATED_AT DATETIME NOT NULL CONSTRAINT DF_APP_USER_CREATED DEFAULT(GETDATE())
    );
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.APP_USER') AND name = 'EMAIL')
    ALTER TABLE dbo.APP_USER ADD EMAIL NVARCHAR(255) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'APP_USER_ROLE')
BEGIN
    CREATE TABLE dbo.APP_USER_ROLE (
        USER_ID NVARCHAR(50) NOT NULL,
        ROLE_CODE NVARCHAR(50) NOT NULL,
        CONSTRAINT PK_APP_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CODE),
        CONSTRAINT FK_APP_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES dbo.APP_USER(USER_ID),
        CONSTRAINT FK_APP_USER_ROLE_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES dbo.APP_ROLE(ROLE_CODE)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DIE_MST')
BEGIN
    CREATE TABLE dbo.DIE_MST (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NOT NULL,
        TOTAL_CAVITY INT NOT NULL
    );
END
GO

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DIE_MST')
   AND NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.DIE_MST') AND name = 'ID')
BEGIN
    SELECT DIE_NO, DIE_NAME, TOTAL_CAVITY
    INTO #DIE_MST_OLD
    FROM dbo.DIE_MST;

    DROP TABLE dbo.DIE_MST;

    CREATE TABLE dbo.DIE_MST (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NOT NULL,
        TOTAL_CAVITY INT NOT NULL
    );

    INSERT INTO dbo.DIE_MST (DIE_NO, DIE_NAME, TOTAL_CAVITY)
    SELECT DIE_NO, DIE_NAME, TOTAL_CAVITY
    FROM #DIE_MST_OLD;

    DROP TABLE #DIE_MST_OLD;
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'ADMIN')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ADMIN', N'Quản trị hệ thống');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'ACCOUNT_MGMT')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ACCOUNT_MGMT', N'Quản lý tài khoản');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'DIE_MST_MGMT')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('DIE_MST_MGMT', N'Quản lý Die Master');
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER WHERE USER_ID = 'admin')
BEGIN
    INSERT INTO dbo.APP_USER (USER_ID, FULL_NAME, PASSWORD_MD5, IS_ACTIVE)
    VALUES ('admin', N'System Administrator', '0192023a7bbd73250516f069df18b500', 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'ADMIN')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'ADMIN');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'ACCOUNT_MGMT')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'ACCOUNT_MGMT');
IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'DIE_MST_MGMT')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'DIE_MST_MGMT');
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_PLAN_FY')
BEGIN
    CREATE TABLE dbo.OHD_PLAN_FY (
        PRODUCT_NO NVARCHAR(50) NULL,
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NULL,
        CAVITY NVARCHAR(50) NULL,
        PLAN_YEAR INT NOT NULL,
        PLAN_MONTH INT NOT NULL,
        FY_SHOTS DECIMAL(18,3) NOT NULL DEFAULT(0)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_MACHINE_RATIO')
BEGIN
    CREATE TABLE dbo.OHD_MACHINE_RATIO (
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NULL,
        CAVITY NVARCHAR(50) NULL,
        PLAN_YEAR INT NOT NULL,
        PLAN_MONTH INT NOT NULL,
        RUN_RATIO DECIMAL(9,3) NOT NULL DEFAULT(0)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_DIE_OUTPUT')
BEGIN
    CREATE TABLE dbo.OHD_DIE_OUTPUT (
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NULL,
        CAVITY NVARCHAR(50) NULL,
        PLAN_YEAR INT NOT NULL,
        PLAN_MONTH INT NOT NULL,
        OUTPUT_QTY DECIMAL(18,3) NOT NULL DEFAULT(0)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_PLAN_MASTER')
BEGIN
    CREATE TABLE dbo.OHD_PLAN_MASTER (
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NULL,
        CAVITY_DETAIL NVARCHAR(50) NULL,
        TOTAL_CAVITY INT NULL,
        PLAN_YEAR INT NOT NULL,
        PLAN_MONTH INT NOT NULL,
        FY_SHOTS DECIMAL(18,3) NOT NULL DEFAULT(0),
        RUN_RATIO DECIMAL(9,3) NOT NULL DEFAULT(0),
        LATEST_SHOT DECIMAL(18,3) NOT NULL DEFAULT(0),
        LATEST_OHD INT NOT NULL DEFAULT(0),
        REQUIRED_QTY DECIMAL(18,3) NOT NULL DEFAULT(0),
        OHD_MOC INT NOT NULL DEFAULT(0)
    );
END
GO


IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_FY') AND name = 'CAVITY' AND system_type_id <> 231)
    ALTER TABLE dbo.OHD_PLAN_FY ALTER COLUMN CAVITY NVARCHAR(50) NULL;
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_MACHINE_RATIO') AND name = 'CAVITY' AND system_type_id <> 231)
    ALTER TABLE dbo.OHD_MACHINE_RATIO ALTER COLUMN CAVITY NVARCHAR(50) NULL;
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_DIE_OUTPUT') AND name = 'CAVITY' AND system_type_id <> 231)
    ALTER TABLE dbo.OHD_DIE_OUTPUT ALTER COLUMN CAVITY NVARCHAR(50) NULL;
GO


IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'CAVITY')
    AND NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'CAVITY_DETAIL')
    EXEC sp_rename 'dbo.OHD_PLAN_MASTER.CAVITY', 'CAVITY_DETAIL', 'COLUMN';
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'CAVITY_DETAIL' AND system_type_id <> 231)
    ALTER TABLE dbo.OHD_PLAN_MASTER ALTER COLUMN CAVITY_DETAIL NVARCHAR(50) NULL;
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'TOTAL_CAVITY')
    ALTER TABLE dbo.OHD_PLAN_MASTER ADD TOTAL_CAVITY INT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'LATEST_SHOT')
    ALTER TABLE dbo.OHD_PLAN_MASTER ADD LATEST_SHOT DECIMAL(18,3) NOT NULL CONSTRAINT DF_OHD_PLAN_MASTER_LATEST_SHOT DEFAULT(0);
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_PLAN_MASTER') AND name = 'LATEST_OHD')
    ALTER TABLE dbo.OHD_PLAN_MASTER ADD LATEST_OHD INT NOT NULL CONSTRAINT DF_OHD_PLAN_MASTER_LATEST_OHD DEFAULT(0);

IF NOT EXISTS (SELECT 1 FROM dbo.APP_ROLE WHERE ROLE_CODE = 'PLAN_MGMT')
    INSERT INTO dbo.APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('PLAN_MGMT', N'Quản lý kế hoạch sản xuất');
GO

IF NOT EXISTS (SELECT 1 FROM dbo.APP_USER_ROLE WHERE USER_ID = 'admin' AND ROLE_CODE = 'PLAN_MGMT')
    INSERT INTO dbo.APP_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 'PLAN_MGMT');
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_ALERT_RULE')
BEGIN
    CREATE TABLE dbo.OHD_ALERT_RULE (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        OWNER_USER_ID NVARCHAR(50) NULL,
        ALERT_CONTENT NVARCHAR(500) NOT NULL,
        ALERT_BG_COLOR NVARCHAR(20) NOT NULL DEFAULT('#FFF3CD'),
        ALERT_FG_COLOR NVARCHAR(20) NOT NULL DEFAULT('#7A4E00'),
        DUE_DAYS_30 INT NOT NULL DEFAULT(30),
        DUE_DAYS_60 INT NOT NULL DEFAULT(60),
        DUE_DAYS_90 INT NOT NULL DEFAULT(90),
        DUE_DAYS_120 INT NOT NULL DEFAULT(120),
        DUE_DAYS_150 INT NOT NULL DEFAULT(150),
        DUE_DAYS_180 INT NOT NULL DEFAULT(180),
        DUE_DAYS_210 INT NOT NULL DEFAULT(210),
        DUE_DAYS_240 INT NOT NULL DEFAULT(240),
        USE_MONTH_FIRST_DAY BIT NOT NULL DEFAULT(1),
        EXACT_DAY_IN_MONTH INT NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_ALERT_PROGRESS')
BEGIN
    CREATE TABLE dbo.OHD_ALERT_PROGRESS (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        DIE_NO NVARCHAR(50) NOT NULL,
        DIE_NAME NVARCHAR(255) NULL,
        TOTAL_CAVITY INT NULL,
        NEXT_OHD_MOC INT NOT NULL,
        TRACK_START_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
        ALERT_CONTENT NVARCHAR(500) NULL,
        ALERT_BG_COLOR NVARCHAR(20) NULL,
        ALERT_FG_COLOR NVARCHAR(20) NULL,
        REVIEW_NOTE NVARCHAR(500) NULL,
        OWNER_USER_ID NVARCHAR(50) NULL,
        COMPLETED_AT DATETIME NULL,
        APPROVED BIT NOT NULL DEFAULT(0),
        APPROVED_AT DATETIME NULL,
        LAST_MAIL_SENT_AT DATETIME NULL,
        CREATED_AT DATETIME NOT NULL DEFAULT(GETDATE())
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'OHD_MAIL_CONFIG')
BEGIN
    CREATE TABLE dbo.OHD_MAIL_CONFIG (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        MAIL_TO NVARCHAR(MAX) NOT NULL DEFAULT(''),
        MAIL_CC NVARCHAR(MAX) NOT NULL DEFAULT(''),
        SUBJECT_TEMPLATE NVARCHAR(500) NOT NULL DEFAULT('Nhắc tiến độ OHD'),
        BODY_TEMPLATE NVARCHAR(MAX) NOT NULL DEFAULT(''),
        SEND_FREQUENCY_DAYS INT NOT NULL DEFAULT(1),
        ENABLED BIT NOT NULL DEFAULT(1),
        LAST_SENT_AT DATETIME NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.OHD_ALERT_RULE)
BEGIN
    INSERT INTO dbo.OHD_ALERT_RULE(OWNER_USER_ID, ALERT_CONTENT, ALERT_BG_COLOR, ALERT_FG_COLOR, DUE_DAYS_30, DUE_DAYS_60, DUE_DAYS_90, DUE_DAYS_120, DUE_DAYS_150, DUE_DAYS_180, DUE_DAYS_210, DUE_DAYS_240, USE_MONTH_FIRST_DAY)
    VALUES ('admin', N'Lập danh sách thay part', '#FFF3CD', '#7A4E00', 78, 103, 78, 108, 78, 103, 78, 128, 1),
           ('admin', N'Hoàn thành đặt mua linh kiện', '#E8F5E9', '#1B5E20', 63, 88, 63, 93, 63, 88, 63, 113, 1),
           ('admin', N'Đã nhận part từ nhà cung cấp', '#E3F2FD', '#0D47A1', 33, 48, 33, 48, 33, 48, 33, 53, 1),
           ('admin', N'Bắt đầu chuẩn bị', '#FCE4EC', '#880E4F', 30, 45, 30, 45, 30, 45, 30, 50, 1),
           ('admin', N'Hoàn thiện part', '#F3E5F5', '#4A148C', 15, 15, 15, 15, 15, 15, 15, 15, 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_ALERT_RULE') AND name = 'ALERT_BG_COLOR')
    ALTER TABLE dbo.OHD_ALERT_RULE ADD ALERT_BG_COLOR NVARCHAR(20) NOT NULL CONSTRAINT DF_OHD_ALERT_RULE_BG DEFAULT('#FFF3CD');
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_ALERT_RULE') AND name = 'ALERT_FG_COLOR')
    ALTER TABLE dbo.OHD_ALERT_RULE ADD ALERT_FG_COLOR NVARCHAR(20) NOT NULL CONSTRAINT DF_OHD_ALERT_RULE_FG DEFAULT('#7A4E00');
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_ALERT_PROGRESS') AND name = 'ALERT_BG_COLOR')
    ALTER TABLE dbo.OHD_ALERT_PROGRESS ADD ALERT_BG_COLOR NVARCHAR(20) NULL;
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.OHD_ALERT_PROGRESS') AND name = 'ALERT_FG_COLOR')
    ALTER TABLE dbo.OHD_ALERT_PROGRESS ADD ALERT_FG_COLOR NVARCHAR(20) NULL;
