/* =====================
   JIGFLOW INIT DATABASE
   ===================== */

IF OBJECT_ID(N'dbo.ROLES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ROLES
    (
        ROLE_CODE       VARCHAR(20)      NOT NULL PRIMARY KEY,
        ROLE_NAME       NVARCHAR(100)    NOT NULL,
        DESCRIPTION     NVARCHAR(255)    NULL,
        CREATED_AT      DATETIME         NOT NULL DEFAULT(GETDATE())
    );
END;

IF OBJECT_ID(N'dbo.USERS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.USERS
    (
        USER_ID         INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USERNAME        VARCHAR(50)       NOT NULL UNIQUE,
        FULL_NAME       NVARCHAR(200)     NOT NULL,
        PASSWORD_HASH   VARCHAR(32)       NOT NULL,
        ROLE_CODE       VARCHAR(20)       NOT NULL,
        EMAIL           VARCHAR(200)      NULL,
        IS_ACTIVE       BIT               NOT NULL DEFAULT(1),
        CREATED_AT      DATETIME          NOT NULL DEFAULT(GETDATE()),
        UPDATED_AT      DATETIME          NULL,
        CONSTRAINT FK_USERS_ROLES FOREIGN KEY(ROLE_CODE) REFERENCES dbo.ROLES(ROLE_CODE)
    );
END;

IF OBJECT_ID(N'dbo.MENUS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.MENUS
    (
        MENU_CODE       VARCHAR(50)       NOT NULL PRIMARY KEY,
        MENU_NAME       NVARCHAR(200)     NOT NULL,
        PARENT_CODE     VARCHAR(50)       NULL,
        SORT_ORDER      INT               NOT NULL DEFAULT(0),
        IS_ACTIVE       BIT               NOT NULL DEFAULT(1)
    );
END;

IF OBJECT_ID(N'dbo.ROLE_PERMISSIONS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ROLE_PERMISSIONS
    (
        ID              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ROLE_CODE       VARCHAR(20)       NOT NULL,
        MENU_CODE       VARCHAR(50)       NOT NULL,
        CAN_VIEW        BIT               NOT NULL DEFAULT(0),
        CAN_CREATE      BIT               NOT NULL DEFAULT(0),
        CAN_EDIT        BIT               NOT NULL DEFAULT(0),
        CAN_DELETE      BIT               NOT NULL DEFAULT(0),
        CREATED_AT      DATETIME          NOT NULL DEFAULT(GETDATE()),
        CONSTRAINT FK_ROLE_PERMISSIONS_ROLES FOREIGN KEY(ROLE_CODE) REFERENCES dbo.ROLES(ROLE_CODE),
        CONSTRAINT FK_ROLE_PERMISSIONS_MENUS FOREIGN KEY(MENU_CODE) REFERENCES dbo.MENUS(MENU_CODE),
        CONSTRAINT UQ_ROLE_MENU UNIQUE(ROLE_CODE, MENU_CODE)
    );
END;



IF OBJECT_ID(N'dbo.JIG_TYPE_MASTER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_TYPE_MASTER
    (
        JIG_TYPE_CODE    VARCHAR(50)       NOT NULL PRIMARY KEY,
        JIG_TYPE_NAME    NVARCHAR(200)     NOT NULL,
        IS_ACTIVE        BIT               NOT NULL DEFAULT(1),
        CREATED_AT       DATETIME          NOT NULL DEFAULT(GETDATE())
    );
END;

IF OBJECT_ID(N'dbo.JIG_TYPE_MASTER', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.JIG_TYPE_MASTER', 'UPDATED_AT') IS NULL
        ALTER TABLE dbo.JIG_TYPE_MASTER ADD UPDATED_AT DATETIME NULL;
END;

IF OBJECT_ID(N'dbo.JIG_DRAWING_MASTER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_DRAWING_MASTER
    (
        DRAWING_CODE VARCHAR(100) NOT NULL PRIMARY KEY,
        DRAWING_NAME NVARCHAR(200) NOT NULL,
        FILE_PATH NVARCHAR(500) NULL,
        IS_ACTIVE BIT NOT NULL DEFAULT(1),
        CREATED_AT DATETIME NOT NULL DEFAULT(GETDATE())
    );
END;

/* ===== Jig master / flow tables ===== */
IF OBJECT_ID(N'dbo.JIG_MASTER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_MASTER
    (
        JIG_ID                  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CONTROL_NO              VARCHAR(100)      NOT NULL,
        JIG_NAME                NVARCHAR(200)     NOT NULL,
        JIG_TYPE                NVARCHAR(100)     NOT NULL,
        JIG_TYPE_CODE           VARCHAR(50)       NULL,
        JIG_SIZE                VARCHAR(50)       NULL,
        USE_PRODUCT             NVARCHAR(300)     NULL,
        PURPOSE_USE             NVARCHAR(300)     NULL,
        LOCATION_CODE           VARCHAR(50)       NULL,
        FACTORY                 VARCHAR(50)       NULL,
        STATUS_USE              NVARCHAR(100)     NULL,
        USE_SECTION             NVARCHAR(100)     NULL,
        LAST_CHECK_DATE         DATE              NULL,
        NEXT_CHECK_PLAN         VARCHAR(20)       NULL,
        CHECK_RESULT            NVARCHAR(50)      NULL,
        CHECK_FREQUENCY         NVARCHAR(50)      NULL,
        IS_ACTIVE               BIT               NOT NULL DEFAULT(1),
        CREATED_BY              VARCHAR(50)       NULL,
        CREATED_AT              DATETIME          NOT NULL DEFAULT(GETDATE()),
        UPDATED_BY              VARCHAR(50)       NULL,
        UPDATED_AT              DATETIME          NULL,
        CONSTRAINT UQ_JIG_MASTER_CONTROL UNIQUE(CONTROL_NO)
    );
END;

IF OBJECT_ID(N'dbo.JIG_REGISTER_REQUEST', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_REGISTER_REQUEST
    (
        REQUEST_ID               INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JIG_ID                   INT               NULL,
        REQUEST_TYPE             VARCHAR(30)       NOT NULL DEFAULT('NEW'),
        REQUEST_STATUS           VARCHAR(30)       NOT NULL DEFAULT('WAITING_APPROVE'),
        REQUEST_REASON           NVARCHAR(500)     NULL,
        REQUEST_BY               VARCHAR(50)       NOT NULL,
        REQUEST_AT               DATETIME          NOT NULL DEFAULT(GETDATE()),
        APPROVE_BY               VARCHAR(50)       NULL,
        APPROVE_AT               DATETIME          NULL,
        APPROVE_NOTE             NVARCHAR(500)     NULL,
        CONSTRAINT FK_REGISTER_REQUEST_JIG FOREIGN KEY(JIG_ID) REFERENCES dbo.JIG_MASTER(JIG_ID)
    );
END;

IF OBJECT_ID(N'dbo.JIG_CHECK_HISTORY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_CHECK_HISTORY
    (
        CHECK_ID                 INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JIG_ID                   INT               NOT NULL,
        CHECK_DATE               DATETIME          NOT NULL DEFAULT(GETDATE()),
        CHECK_RESULT             NVARCHAR(50)      NOT NULL,
        CHECK_NOTE               NVARCHAR(500)     NULL,
        CHECK_BY                 VARCHAR(50)       NOT NULL,
        CHECKER_BY               VARCHAR(50)       NULL,
        APPROVE_BY               VARCHAR(50)       NULL,
        APPROVE_AT               DATETIME          NULL,
        REPORT_FILE              NVARCHAR(500)     NULL,
        CONSTRAINT FK_CHECK_HISTORY_JIG FOREIGN KEY(JIG_ID) REFERENCES dbo.JIG_MASTER(JIG_ID)
    );
END;

IF OBJECT_ID(N'dbo.JIG_CHECK_HISTORY', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.JIG_CHECK_HISTORY', 'CHECKER_BY') IS NULL
        ALTER TABLE dbo.JIG_CHECK_HISTORY ADD CHECKER_BY VARCHAR(50) NULL;
    IF COL_LENGTH('dbo.JIG_CHECK_HISTORY', 'APPROVE_BY') IS NULL
        ALTER TABLE dbo.JIG_CHECK_HISTORY ADD APPROVE_BY VARCHAR(50) NULL;
    IF COL_LENGTH('dbo.JIG_CHECK_HISTORY', 'APPROVE_AT') IS NULL
        ALTER TABLE dbo.JIG_CHECK_HISTORY ADD APPROVE_AT DATETIME NULL;
    IF COL_LENGTH('dbo.JIG_CHECK_HISTORY', 'REPORT_FILE') IS NULL
        ALTER TABLE dbo.JIG_CHECK_HISTORY ADD REPORT_FILE NVARCHAR(500) NULL;
END;

IF OBJECT_ID(N'dbo.JIG_CANCEL_REQUEST', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_CANCEL_REQUEST
    (
        CANCEL_ID                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JIG_ID                   INT               NOT NULL,
        REQUEST_STATUS           VARCHAR(30)       NOT NULL DEFAULT('WAITING_APPROVE'),
        CANCEL_REASON            NVARCHAR(500)     NULL,
        REQUEST_BY               VARCHAR(50)       NOT NULL,
        REQUEST_AT               DATETIME          NOT NULL DEFAULT(GETDATE()),
        APPROVE_BY               VARCHAR(50)       NULL,
        APPROVE_AT               DATETIME          NULL,
        APPROVE_NOTE             NVARCHAR(500)     NULL,
        CONSTRAINT FK_CANCEL_REQUEST_JIG FOREIGN KEY(JIG_ID) REFERENCES dbo.JIG_MASTER(JIG_ID)
    );
END;

IF OBJECT_ID(N'dbo.JIG_EDIT_HISTORY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.JIG_EDIT_HISTORY
    (
        HISTORY_ID         INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        JIG_NAME           NVARCHAR(200)     NULL,
        OLD_CONTROL_NO     VARCHAR(100)      NULL,
        NEW_CONTROL_NO     VARCHAR(100)      NULL,
        JIG_TYPE_CODE      VARCHAR(50)       NULL,
        JIG_SIZE           VARCHAR(50)       NULL,
        USE_PRODUCT        NVARCHAR(300)     NULL,
        PURPOSE_USE        NVARCHAR(300)     NULL,
        LOCATION_CODE      VARCHAR(50)       NULL,
        DEPARTMENT         NVARCHAR(100)     NULL,
        FACTORY            VARCHAR(50)       NULL,
        UPDATED_BY         VARCHAR(50)       NULL,
        UPDATED_AT         DATETIME          NOT NULL DEFAULT(GETDATE())
    );
END;

IF OBJECT_ID(N'dbo.FORM_MASTER', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FORM_MASTER
    (
        FORM_ID                  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        FORM_CODE                VARCHAR(100)      NOT NULL UNIQUE,
        FORM_NAME                NVARCHAR(200)     NOT NULL,
        FORM_VERSION             VARCHAR(20)       NULL,
        DESCRIPTION              NVARCHAR(500)     NULL,
        TEMPLATE_FILE_PATH       NVARCHAR(500)     NULL,
        PART_NAME_CELL           VARCHAR(20)       NULL,
        CONTROL_NO_CELL          VARCHAR(20)       NULL,
        CHECK_DATE_CELL          VARCHAR(20)       NULL,
        IS_DEFAULT               BIT               NOT NULL DEFAULT(0),
        IS_ACTIVE                BIT               NOT NULL DEFAULT(1),
        CREATED_AT               DATETIME          NOT NULL DEFAULT(GETDATE()),
        UPDATED_AT               DATETIME          NULL
    );
END;
IF COL_LENGTH('dbo.FORM_MASTER', 'TEMPLATE_FILE_PATH') IS NULL
    ALTER TABLE dbo.FORM_MASTER ADD TEMPLATE_FILE_PATH NVARCHAR(500) NULL;
IF COL_LENGTH('dbo.FORM_MASTER', 'PART_NAME_CELL') IS NULL
    ALTER TABLE dbo.FORM_MASTER ADD PART_NAME_CELL VARCHAR(20) NULL;
IF COL_LENGTH('dbo.FORM_MASTER', 'CONTROL_NO_CELL') IS NULL
    ALTER TABLE dbo.FORM_MASTER ADD CONTROL_NO_CELL VARCHAR(20) NULL;
IF COL_LENGTH('dbo.FORM_MASTER', 'CHECK_DATE_CELL') IS NULL
    ALTER TABLE dbo.FORM_MASTER ADD CHECK_DATE_CELL VARCHAR(20) NULL;
IF COL_LENGTH('dbo.FORM_MASTER', 'IS_DEFAULT') IS NULL
    ALTER TABLE dbo.FORM_MASTER ADD IS_DEFAULT BIT NOT NULL CONSTRAINT DF_FORM_MASTER_IS_DEFAULT DEFAULT(0);

IF COL_LENGTH('dbo.JIG_DRAWING_MASTER', 'UPDATED_AT') IS NULL
    ALTER TABLE dbo.JIG_DRAWING_MASTER ADD UPDATED_AT DATETIME NULL;

IF COL_LENGTH('dbo.JIG_TYPE_MASTER', 'JIG_TYPE_MAIN') IS NULL
    ALTER TABLE dbo.JIG_TYPE_MASTER ADD JIG_TYPE_MAIN VARCHAR(30) NULL;
IF COL_LENGTH('dbo.JIG_TYPE_MASTER', 'DEFAULT_DRAWING_CODE') IS NULL
    ALTER TABLE dbo.JIG_TYPE_MASTER ADD DEFAULT_DRAWING_CODE VARCHAR(100) NULL;



/* ===== Ensure required columns for JIG function list ===== */
IF COL_LENGTH('dbo.JIG_MASTER', 'NEXT_CHECK_PLAN_DATE') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD NEXT_CHECK_PLAN_DATE DATE NULL;

IF COL_LENGTH('dbo.JIG_MASTER', 'LAST_CHECK_DATE') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD LAST_CHECK_DATE DATE NULL;

IF COL_LENGTH('dbo.JIG_MASTER', 'CHECK_RESULT') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD CHECK_RESULT NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.JIG_MASTER', 'CHECK_FREQUENCY') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD CHECK_FREQUENCY NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.JIG_MASTER', 'JIG_TYPE_CODE') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD JIG_TYPE_CODE VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_MASTER', 'FACTORY') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD FACTORY VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_MASTER', 'PURPOSE_USE') IS NULL
    ALTER TABLE dbo.JIG_MASTER ADD PURPOSE_USE NVARCHAR(300) NULL;


IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'DEPARTMENT') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD DEPARTMENT VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'FACTORY') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD FACTORY VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'MANAGEMENT_NO') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD MANAGEMENT_NO VARCHAR(100) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'REPORT_FORM_CODE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD REPORT_FORM_CODE VARCHAR(100) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'FIRST_CHECK_RESULT_FILE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD FIRST_CHECK_RESULT_FILE NVARCHAR(500) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'DRAWING_CODE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD DRAWING_CODE VARCHAR(100) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_NAME') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_NAME NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_TYPE_CODE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_TYPE_CODE VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_SIZE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_SIZE VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'USE_PRODUCT') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD USE_PRODUCT NVARCHAR(300) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'PURPOSE_USE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD PURPOSE_USE NVARCHAR(300) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'LOCATION_CODE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD LOCATION_CODE VARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'LAST_CHECK_DATE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD LAST_CHECK_DATE DATE NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'CHECK_FREQUENCY') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD CHECK_FREQUENCY NVARCHAR(50) NULL;
IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'STATUS_USE') IS NULL
    ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD STATUS_USE NVARCHAR(100) NULL;

/* ===== Safety migration for legacy databases (run again-safe) ===== */
IF OBJECT_ID(N'dbo.JIG_REGISTER_REQUEST', N'U') IS NOT NULL
BEGIN
    DECLARE @SQL_MIGRATION_REGISTER NVARCHAR(MAX) = N'';

    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'DEPARTMENT') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD DEPARTMENT VARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'FACTORY') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD FACTORY VARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'MANAGEMENT_NO') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD MANAGEMENT_NO VARCHAR(100) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_NAME') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_NAME NVARCHAR(200) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_TYPE_CODE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_TYPE_CODE VARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'JIG_SIZE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD JIG_SIZE VARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'USE_PRODUCT') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD USE_PRODUCT NVARCHAR(300) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'PURPOSE_USE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD PURPOSE_USE NVARCHAR(300) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'LOCATION_CODE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD LOCATION_CODE VARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'LAST_CHECK_DATE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD LAST_CHECK_DATE DATE NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'CHECK_FREQUENCY') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD CHECK_FREQUENCY NVARCHAR(50) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'REPORT_FORM_CODE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD REPORT_FORM_CODE VARCHAR(100) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'FIRST_CHECK_RESULT_FILE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD FIRST_CHECK_RESULT_FILE NVARCHAR(500) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'DRAWING_CODE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD DRAWING_CODE VARCHAR(100) NULL;';
    IF COL_LENGTH('dbo.JIG_REGISTER_REQUEST', 'STATUS_USE') IS NULL
        SET @SQL_MIGRATION_REGISTER += N'ALTER TABLE dbo.JIG_REGISTER_REQUEST ADD STATUS_USE NVARCHAR(100) NULL;';

    IF LEN(@SQL_MIGRATION_REGISTER) > 0
        EXEC sys.sp_executesql @SQL_MIGRATION_REGISTER;
END;

/* ===== Seed base roles/users ===== */
IF NOT EXISTS (SELECT 1 FROM dbo.ROLES WHERE ROLE_CODE = 'SYSTEM_ADMIN')
    INSERT INTO dbo.ROLES(ROLE_CODE, ROLE_NAME, DESCRIPTION)
    VALUES ('SYSTEM_ADMIN', N'System Admin', N'Toàn quyền hệ thống');

IF NOT EXISTS (SELECT 1 FROM dbo.ROLES WHERE ROLE_CODE = 'APPROVER')
    INSERT INTO dbo.ROLES(ROLE_CODE, ROLE_NAME, DESCRIPTION)
    VALUES ('APPROVER', N'Approver', N'Có quyền duyệt nghiệp vụ');

IF NOT EXISTS (SELECT 1 FROM dbo.ROLES WHERE ROLE_CODE = 'MEMBER')
    INSERT INTO dbo.ROLES(ROLE_CODE, ROLE_NAME, DESCRIPTION)
    VALUES ('MEMBER', N'Member', N'Quyền cơ bản');

IF NOT EXISTS (SELECT 1 FROM dbo.USERS WHERE USERNAME = 'admin')
    INSERT INTO dbo.USERS(USERNAME, FULL_NAME, PASSWORD_HASH, ROLE_CODE, EMAIL, IS_ACTIVE)
    VALUES ('admin', N'JigFlow Admin', 'e10adc3949ba59abbe56e057f20f883e', 'SYSTEM_ADMIN', NULL, 1); -- 123456



/* ===== Seed JIG type master ===== */
IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'JIG_FUNCTION')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('JIG_FUNCTION', N'Jig chức năng', 'FUNCTION');
IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'JIG_SUPPORT')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('JIG_SUPPORT', N'Jig gá-Jig hỗ trợ', 'VISUAL');
IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'JIG_PRODUCT_DISTINGUISH')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('JIG_PRODUCT_DISTINGUISH', N'Jig phân biệt sản phẩm', 'VISUAL');
IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'JIG_HLC')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('JIG_HLC', N'Jig HLC', 'VISUAL');

IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'BRACKET_1')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('BRACKET_1', N'Bracket 1', 'FUNCTION');
IF NOT EXISTS (SELECT 1 FROM dbo.JIG_TYPE_MASTER WHERE JIG_TYPE_CODE = 'BRACKET_2')
    INSERT INTO dbo.JIG_TYPE_MASTER(JIG_TYPE_CODE, JIG_TYPE_NAME, JIG_TYPE_MAIN) VALUES ('BRACKET_2', N'Bracket 2', 'FUNCTION');

UPDATE dbo.JIG_TYPE_MASTER SET JIG_TYPE_MAIN = 'FUNCTION' WHERE JIG_TYPE_CODE IN ('JIG_FUNCTION','BRACKET_1','BRACKET_2') AND ISNULL(JIG_TYPE_MAIN,'') = '';
UPDATE dbo.JIG_TYPE_MASTER SET JIG_TYPE_MAIN = 'VISUAL' WHERE JIG_TYPE_CODE IN ('JIG_SUPPORT','JIG_PRODUCT_DISTINGUISH','JIG_HLC') AND ISNULL(JIG_TYPE_MAIN,'') = '';

IF NOT EXISTS (SELECT 1 FROM dbo.JIG_DRAWING_MASTER WHERE DRAWING_CODE = 'DWG-001')
    INSERT INTO dbo.JIG_DRAWING_MASTER(DRAWING_CODE, DRAWING_NAME, FILE_PATH) VALUES ('DWG-001', N'Bản vẽ Jig 001', NULL);


/* ===== Seed menu items matching ribbon ===== */
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_FUNCTION_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_FUNCTION_LIST', N'Jig chức năng', NULL, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_VISUAL_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_VISUAL_LIST', N'Jig ngoại quan', NULL, 2);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_REGISTER_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_REGISTER_LIST', N'Đăng ký Jig', NULL, 3);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_NEW_WAITING_APPROVE_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_NEW_WAITING_APPROVE_LIST', N'Jig mới chờ duyệt', NULL, 4);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_REGISTER_HISTORY_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_REGISTER_HISTORY_LIST', N'Lịch sử đăng ký Jig', NULL, 5);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_NOT_CHECKED_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_NOT_CHECKED_LIST', N'Jig chưa được kiểm tra', NULL, 6);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_CHECK_HISTORY_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_CHECK_HISTORY_LIST', N'Lịch sử kiểm tra Jig', NULL, 7);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_CANCEL_REGISTER')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_CANCEL_REGISTER', N'Đăng ký hủy Jig', NULL, 8);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_CANCEL_WAITING_APPROVE_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_CANCEL_WAITING_APPROVE_LIST', N'Jig hủy chờ duyệt', NULL, 9);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_CANCEL_HISTORY_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_CANCEL_HISTORY_LIST', N'Lịch sử hủy Jig', NULL, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'JIG_DRAWING_LIST')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('JIG_DRAWING_LIST', N'Bản vẽ Jig', NULL, 11);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'FORM_MASTER')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('FORM_MASTER', N'Form Master', NULL, 12);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'ACCOUNT_MANAGEMENT')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('ACCOUNT_MANAGEMENT', N'Quản lý tài khoản', NULL, 13);
IF NOT EXISTS (SELECT 1 FROM dbo.MENUS WHERE MENU_CODE = 'CHANGE_PASSWORD')
    INSERT INTO dbo.MENUS(MENU_CODE, MENU_NAME, PARENT_CODE, SORT_ORDER) VALUES ('CHANGE_PASSWORD', N'Đổi mật khẩu', NULL, 14);

/****** Grant all menus for SYSTEM_ADMIN ******/
INSERT INTO dbo.ROLE_PERMISSIONS(ROLE_CODE, MENU_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE)
SELECT 'SYSTEM_ADMIN', M.MENU_CODE, 1, 1, 1, 1
FROM dbo.MENUS M
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.ROLE_PERMISSIONS RP
    WHERE RP.ROLE_CODE = 'SYSTEM_ADMIN' AND RP.MENU_CODE = M.MENU_CODE
);

/****** Grant approve role on operational menus ******/
INSERT INTO dbo.ROLE_PERMISSIONS(ROLE_CODE, MENU_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE)
SELECT 'APPROVER', M.MENU_CODE, 1, 1, 1, 0
FROM dbo.MENUS M
WHERE M.MENU_CODE IN
(
    'JIG_FUNCTION_LIST','JIG_VISUAL_LIST','JIG_REGISTER_LIST','JIG_NEW_WAITING_APPROVE_LIST',
    'JIG_REGISTER_HISTORY_LIST','JIG_NOT_CHECKED_LIST','JIG_CHECK_HISTORY_LIST','JIG_CANCEL_REGISTER',
    'JIG_CANCEL_WAITING_APPROVE_LIST','JIG_CANCEL_HISTORY_LIST','JIG_DRAWING_LIST','FORM_MASTER','CHANGE_PASSWORD'
)
AND NOT EXISTS
(
    SELECT 1
    FROM dbo.ROLE_PERMISSIONS RP
    WHERE RP.ROLE_CODE = 'APPROVER' AND RP.MENU_CODE = M.MENU_CODE
);

/****** Grant view-only for MEMBER on operational menus ******/
INSERT INTO dbo.ROLE_PERMISSIONS(ROLE_CODE, MENU_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE)
SELECT 'MEMBER', M.MENU_CODE, 1, 0, 0, 0
FROM dbo.MENUS M
WHERE M.MENU_CODE IN
(
    'JIG_FUNCTION_LIST','JIG_VISUAL_LIST','JIG_REGISTER_LIST','JIG_NEW_WAITING_APPROVE_LIST',
    'JIG_REGISTER_HISTORY_LIST','JIG_NOT_CHECKED_LIST','JIG_CHECK_HISTORY_LIST','JIG_CANCEL_REGISTER',
    'JIG_CANCEL_WAITING_APPROVE_LIST','JIG_CANCEL_HISTORY_LIST','JIG_DRAWING_LIST','FORM_MASTER','CHANGE_PASSWORD'
)
AND NOT EXISTS
(
    SELECT 1
    FROM dbo.ROLE_PERMISSIONS RP
    WHERE RP.ROLE_CODE = 'MEMBER' AND RP.MENU_CODE = M.MENU_CODE
);
